### ISSUE TITLE
API Key and a few features

### ISSUE THREAD

**Issue by rNoz** [Spring3/redshape#12]
Hi,

I tried your app for 10 minutes, and it is great. Thank you. But I have a few questions:

I am thinking if work on this project (fork) and support a few things I would like. Do you accept PR?

1. I don't like to write my username and password. Would be better to use the user API Key.
2. Support multiple trackers. My workflow usually involves time entries of many hours. And suddenly, a client needs something so urgent that I don't have even time to stop and write everything I did. Therefore, what I would do is pause the current tracker, and start a new one. Then, when I finish this new tracker, I would resume the previous one. 
3. When I use a tracker and stop it, the "Hours" is freezed/disabled. I would like to change it.
4. When I use a tracker and stop it, if I close the window, there is no confirmation.
5. Support "human" time durations. I would like to write the durations like "1h 20m", instead of "1.33" hours.
5. Be able to minimize to tray. Most of the time this app could be running in the background and just keep tracking of the time.

And the most important one because I think it could be a harder task: can you define a simple guideline of what to do if we want to port this application to mobile (hybrid, like cordova)? What would you do in general, like a simple roadmap?

I appreciate your comments.

PS: In case I am doing something wrong, when I ran the tests I got:

```
Snapshot Summary
 › 13 snapshots failed from 13 test suites. Inspect your code changes or run `yarn test -u` to update them.

Test Suites: 13 failed, 32 passed, 45 total
Tests:       17 failed, 227 passed, 244 total
Snapshots:   13 failed, 10 passed, 23 total
Time:        74.659s

$ node --version
v10.17.0

$ yarn --version
1.21.0

$ npm --version
6.12.1

$ electron --version
v7.1.3
```

**Comment by rNoz** [comment]
Hi. First, it is the first time I work with react, therefore, it won't be the most convenient way for sure... but well. I came from Vue. At least today I did the login with API Key and repairing some bugs regarding the Route/Component (reducing Electron console.log errors).

Probably doing the tests will take much more time.

I don't know if you will accept PR. Still, as I forked this project, I will try to progress a bit.  But I would like to know how you format you project automatically, and if you will work on repairing your tests. It is a bit difficult to know, while developing, if I am generating new errors. Today was "easy" because I focused mainly in the LoginView. But currently, the AppView has around 14 errors.

![2019-12-22_20-54](https://user-images.githubusercontent.com/8237539/71326631-ce054880-24fd-11ea-8998-210df64bbdae.png)

**Comment by rNoz** [comment]
Hi,

I have performed these tasks:
- When I use a tracker and stop it, the "Hours" is freezed/disabled. I would like to change it.
- When I use a tracker and stop it, if I close the window, there is no confirmation.
- Support "human" time durations. I would like to write the durations like "1h 20m", instead of "1.33" hours.
- Be able to minimize to tray. Most of the time this app could be running in the background and just keep tracking of the time.

Apart from that, a few bugfixes.

Also, I would like to speak about a few things after working 3-4 days in your project, like what is the best way to implement the Modal/Dialog (check TimeEntryModal) and how to solve the 'JS out of heap memory', when using one snapshot (present in the last feature-commit, so I disabled that specific snapshot). 

Will you consider a PR? You can inspect my fork.

Note: I will upload tomorrow a few captures of the new features in this issue.

**Comment by Spring3** [comment]
Hello @rNoz . Sorry for a late response. I have been working on this application because we used redmine in the previous company I worked at. Eventually, we moved from it and I am also working at a different company that also does not use redmine. So at the moment, this application is not really a priority or something that I would like to spend time improving.

I do accept PRs. If you use the app and are willing to improve it or add new features - why not. I can even add you as a contributor, so you have the direct access to this repo. However, at the time this app was written, I maybe didn't know some techniques and had less experience with react, so some parts of the app could be re-written in a better, more performant way.

However, I will try to answer all of your questions here

1.1) If I am not mistaken, it already uses the API key. Username / password is required to get one from the API. It does not keep it in any form anywhere after the API key is retrieved. However, if you are talking about just copy-pasting the API key instead of the login form, then sure, I think that the users should decide what fits them most and should be able to pick either option.

1.2) When I was working on this initial version of the application, I considered the use case when you always track 1 task. So, the flow was -> track -> pause/unpause -> submit -> comment/done. Thing is that the time is only submitted to the API once you are done with tracking. So if you pause one tracker, but start to work on another one, this can lead to a situation, when you will forget about that other one paused tracker and that time won't be submitted at all.

1.3) That's the point of tracking time :) It shows you exactly the time that you tracked. This of course means that whenever you make a pause, you have to explicitly pause the tracker and then continue it once you are back. However, you can also change the number of tracked hours once you click on the submitted time from the right side of the menu and then edit it there.

1.4) Indeed, the confirmation window should be added

1.5) That's a good thing to add. I just displayed the values, supported by the redmine API.

1.6) I agree. That was planned at some point.

About mobile - I am not a mobile developer, so I've never built a mobile app with something like cordova or similar. I believe that electron does not work with mobile and hence a mobile app should be implemented from scratch. I would also imagine that user interactions and menus will be completely different.

**Comment by Spring3** [comment]
I will try to check your fork when I have some more time. But feel free to open a PR with your changes. It will be easier to review

**Comment by Spring3** [comment]
You were asking about the roadmap that I had. Here's a list of stuff that I wanted to implement over time

v1.1
- subtasks
- parent tasks

v1.2
- issues page

v1.3
- performance statistics chart
- web worker for live comments update

v1.4
- cache as store
- cache update
- offline update queue
- offline update queue item edit 
- offline update queue item delete
- theme selection

**Comment by rNoz** [comment]
Hi, @Spring3.

Thanks for your response. I really appreciate that you consider adding me as contributor. Indeed, I won't have much time to do many more improvements because I dedicated almost 1 week to this project, just for fun and functionality. Also, the company where I work allow us to contribute in open source projects using work time, so, most of the credit would be also towards them (Group4Layers). 

I am quite happy with the features and bugfixes done, but I have to warn you: I am new to React, so, probably you will find better approaches or techniques. Still, I would appreciate if you add me as contributor of your project, or mention me somewhere (maybe in the readme or about, something like rNoz from Group4Layers) :)

1.1. Exactly. I referred as the first login usage.
1.2. I was imaging the timers as a "stack", usually only 0 or 1 timer, but eventually, for some period, even 2 (urgent tasks in between), so, nothing would be problematic about forgetting (user will see the timers, only a single one running). Still, I haven't implemented this feature (and I won't in the near future), mainly because it is a small use case and the app has a single Timer in a few components, so I will need another couple of days to work on it.
1.3. I know, but it is true that is common to just forget smaller periods and at the end you have to do minor corrections (eg. forgot to pause during coffee break 15m, etc). So you can do corrections before submitting.

Yes, mobile would need more time. It is true that only a little portion of the app is electron-focused, so, it wouldn't require much effort to port to cordova. But still could be a 1-2 week work time to do it properly. 

Now, I paste here the main captures showing the features added. I have to say that I implemented in the last 2 days another two features:
- Optimization to avoid getting timer intervals being ticked every second when the window is hidden.
- Tray supports pause/resume the current timer. It was a bit tricky but it is done. It uses IPC/Electron specific code.

Sorry if I don't add enough tests for you. You can modify everything you want. I tested the app, but for sure, don't trust me and review it :) Our team will try in stage/production the app during the next days. In case we find some error, we will notify you with changes.

Login accept API/username+password:
![login_mode_api](https://user-images.githubusercontent.com/8237539/71561554-8db34680-2a78-11ea-8587-eff3fd12d371.png)


Duration: you can use hours, and it is rounded as it will be used in Redmine
![accept_hours](https://user-images.githubusercontent.com/8237539/71561584-bb988b00-2a78-11ea-8c5c-4fd28c1d3919.png)

Duration: hours are not positive enough (15s rounded => 0)
![error_nonpositive_enough](https://user-images.githubusercontent.com/8237539/71561569-b20f2300-2a78-11ea-86c2-c32fe35db1e5.png)

Duration: empty
![error_empty](https://user-images.githubusercontent.com/8237539/71561590-dcf97700-2a78-11ea-8650-ced045c4a048.png)

Duration: negative
![error_negative](https://user-images.githubusercontent.com/8237539/71561597-e1be2b00-2a78-11ea-9b5c-5a27f63ed85b.png)

Duration: duration format example 1
![accept_duration_1](https://user-images.githubusercontent.com/8237539/71561609-f69abe80-2a78-11ea-947f-1666c71eaead.png)

Duration: duration format example 2
![accept_duration_2](https://user-images.githubusercontent.com/8237539/71561587-ceab5b00-2a78-11ea-8fef-f39d4c4cbfe8.png)

A TimeEntry:
![timeentries](https://user-images.githubusercontent.com/8237539/71561620-15995080-2a79-11ea-985c-7b390297167f.png)

When it is clicked, it is automatically converted to the most comfortable duration format (Also, validation is performed per field - onBlur):
![timeentries_modal_duration](https://user-images.githubusercontent.com/8237539/71561624-28138a00-2a79-11ea-977f-07cd894085d7.png)

When Tracking an issue:
![timer](https://user-images.githubusercontent.com/8237539/71561629-35c90f80-2a79-11ea-9f87-05e42f49ca5e.png)

And it is stopped, it is properly filled:
![timer_stop_modal_duration](https://user-images.githubusercontent.com/8237539/71561630-395c9680-2a79-11ea-8c3f-0e99d51801d3.png)

Added info for duration:
![tooltip](https://user-images.githubusercontent.com/8237539/71561636-4c6f6680-2a79-11ea-8ada-5d5ce4a8973f.png)

When closing the modal of a modified entry or non saved entry (stopped), we need to confirm:
![timeentreymodal_confirm_modified](https://user-images.githubusercontent.com/8237539/71561640-5db87300-2a79-11ea-9fc0-6fb9cafe601f.png)

Example of the optimization (debug while developing; these messages are not present in the code):
![tracker_optimization](https://user-images.githubusercontent.com/8237539/71561645-7032ac80-2a79-11ea-96d1-caca8e3656f7.png)

Tray with pause/resume button of current timer (long/short issue subject):
![tray_pause_long](https://user-images.githubusercontent.com/8237539/71561651-7b85d800-2a79-11ea-9712-166e7dc850f7.png)
![tray_resume_short](https://user-images.githubusercontent.com/8237539/71561655-7d4f9b80-2a79-11ea-8251-a11058c1d400.png)

**Comment by rNoz** [comment]
Hi, @Spring3 
At the end the company allowed me to work a few days more on this repo :)
So, I worked in more features. I have uploaded everything in my fork. Have a look there (README and git log). If you want me to update the PR with everything, just let me know :)
My co-workers liked the changes, so, some of us are currently using internally to test it even more.
Happy new year!

**Comment by Spring3** [comment]
Hello, @rNoz .
Thanks for your huge contribution. I was planning to review your work these weekends, and hopefully merge it soon. 

Happy new year to you too!
